### ISSUE TITLE
Does not work . Trying on a V100

### ISSUE THREAD

**Issue by computersrmyfriends** [metavoiceio/metavoice-src#102]
Followed the documentation "exactly step by step". Tried in fresh environments but does not work out of the box.

```
/metavoice-src/fam/llm/fast_inference_utils.py", line 131, in prefill
    logits = model(x, spk_emb, input_pos)
  File "/opt/conda/envs/metavoice/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by lucapericlp** [comment]
Hey @computersrmyfriends, thanks for the issue. It seems like you're using a `conda` environment instead of the `poetry` one I would have expected (as indicated by `/opt/conda/envs/metavoice/`). 

Could you `poetry env list`, take the relevant env & `poetry env remove {env-name}`, `conda deactivate` & then `poetry install && poetry run pip install torch==2.2.1 torchaudio==2.2.1`? You should be able to then run [the usage](https://github.com/metavoiceio/metavoice-src?tab=readme-ov-file#usage) commands successfully. If this isn't the case, let me know & I'll try my best to get you up & running again ASAP.

**Comment by computersrmyfriends** [comment]
Thanks I got it to finally work after trying it using /bin/python3 -m pip outside conda.

Now,installation has suceeded. However, I have one more query. It says it supports long form but it does not generate more than 10 to 12 seconds? Can I use this for an audio book?

**Comment by lucapericlp** [comment]
Great to hear! Long-form synthesis is coming soon, we'll be sharing a sneak peak on our socials ([twitter](https://twitter.com/metavoiceio)) soon or you can just keep an eye on this repo for when it drops! 

Going to close this issue, feel free to open another if you run into any other issues.
