### ISSUE TITLE
Is it possible to run this model on 4Gb memory GPU?

### ISSUE THREAD

**Issue by I7yzan** [metavoiceio/metavoice-src#66]

**Comment by sidroopdaska** [comment]
Unlikely on GPU with 4GB VRAM. I believe (yet to be tested) we can fit this in on a GPU with 8/12GB VRAM.

**Comment by vatsalaggarwal** [comment]
I don't think 8GB/12GB would work right now... but you could probably replace Multiband Diffusion with Vocos (https://github.com/gemelo-ai/vocos) and make it work on 12GB. MBD is a ~5GB model whereas Vocos is ~40MB, so that make enough room... There is some quality impact from doing this though.

**Comment by pipertownley** [comment]
Hi! First, huge thanks for making this project! I'm rather green with ML in general but I'm very interested in running metavoice on an 8gb GPU, and I'm more than willing to try contributing in this area. 

I could use a little help understanding all the models in use and how they fit together. I'd like to see if 4bit quantization could be applied anywhere to bring the footprint down further. Without really understanding everything going on, it feels like a lot of memory compared to, say, mistral:7b, which takes up a bit over 4GB (using 4bit quantizing).

Is there anywhere I can get a good break down of the architecture (besides trying to map it out with the code?)
Do you have any other memory saving tips like swapping MBD for Vocos?

Much thanks!

**Comment by pipertownley** [comment]
> Is there anywhere I can get a good break down of the architecture (besides trying to map it out with the code?) Do you have any other memory saving tips like swapping MBD for Vocos?

*head desk* my apologies. 

## Architecture
We predict EnCodec tokens from text, and speaker information. This is then diffused up to the waveform level, with post-processing applied to clean up the audio.

* We use a causal GPT to predict the first two hierarchies of EnCodec tokens. Text and audio are part of the LLM context. Speaker information is passed via conditioning at the token embedding layer. This speaker conditioning is obtained from a separately trained speaker verification network.
  - The two hierarchies are predicted in a "flattened interleaved" manner, we predict the first token of the first hierarchy, then the first token of the second hierarchy, then the second token of the first hierarchy, and so on.
  - We use condition-free sampling to boost the cloning capability of the model.
  - The text is tokenised using a custom trained BPE tokeniser with 512 tokens.
  - Note that we've skipped predicting semantic tokens as done in other works, as we found that this isn't strictly necessary.
* We use a non-causal (encoder-style) transformer to predict the rest of the 6 hierarchies from the first two hierarchies. This is a super small model (~10Mn parameters), and has extensive zero-shot generalisation to most speakers we've tried. Since it's non-causal, we're also able to predict all the timesteps in parallel.
* We use multi-band diffusion to generate waveforms from the EnCodec tokens. We noticed that the speech is clearer than using the original RVQ decoder or VOCOS. However, the diffusion at waveform level leaves some background artifacts which are quite unpleasant to the ear. We clean this up in the next step.
* We use DeepFilterNet to clear up the artifacts introduced by the multi-band diffusion.

**Comment by sidroopdaska** [comment]
Closing this ticket from inactivity
